### ISSUE TITLE
how do artifacts work with this plugin?

### ISSUE THREAD

**Issue by nhooyr** [buildkite-plugins/docker-buildkite-plugin#104]
Is it required to use `buildkite-agent artifact upload` versus using the yaml `artifact_paths` field?

**Comment by nhooyr** [comment]
I guess what I actually mean to ask is do does the artifact upload occur inside or outside the docker container?

**Comment by lox** [comment]
Depends on whether you want artifacts from inside the container or outside the container @nhooyr. The agent running the job (outside of the docker container) will process artifacts from `artifact_paths`, but you will need to use host bind mounts to get them out of the container. If you want to upload them from inside the container, you. can use `buildkite-agent artifact upload` directly.
