### ISSUE TITLE
Robustness to registry issues

### ISSUE THREAD

**Issue by dhalperi** [buildkite-plugins/docker-buildkite-plugin#106]
Docker registry seems to have had a ton of issues in the last few days. It would be nice if the Docker plugin itself had retries and could be reliable.

I know we can retry steps based on exit codes, but trying to keep our scripts and plugin setup exit codes non-overlapping seems like a tough challenge.

Examples:
* https://buildkite.com/batfish/pybatfish-pre-commit/builds/849#52d71847-31a6-447f-94c4-8499abe5d154
* https://buildkite.com/batfish/pybatfish-pre-commit/builds/814#1f25c187-4d59-4c4c-9c95-847f13151d19
* https://buildkite.com/batfish/batfish-pre-commit/builds/2407#5f82824c-d3db-416f-a144-eb5eb3c8cc40

(The containers in question are public, so 503 seems like an invalid response code).

**Comment by lox** [comment]
Sorry you are having issues with Docker Hub (assuming it's docker hub, as it's generally flakey). 

We support `pull-retries` in this plugin, but it doesn't seem to be documented. I'll add it! Were you having issues with pull or push?

**Comment by dhalperi** [comment]
Yes, issues with pull. Will check out the mentioned flag! Thanks.

**Comment by lox** [comment]
It only applies when `always-pull` is set to true, but it looks like that might work for your usecase? See https://github.com/buildkite-plugins/docker-buildkite-plugin/pull/107

**Comment by dhalperi** [comment]
Hmm , interesting! We already have `always-pull` true. Maybe it's so flaky that 3 isn't enough?

In the logs (which are public) linked above, we don't see any output like you might expect from here: https://github.com/buildkite-plugins/docker-buildkite-plugin/commit/dfc45d1ae281fff19dc32e689046c4019d0a5e6b#diff-7a7c160f9b73cfeaf4d8b93aee769fc1R20

is that expected?

**Comment by dhalperi** [comment]
Wait, PEBKAC -- we're on v2.2.0, this is in 3.0.0. Thanks!

**Comment by lox** [comment]
Hooray! Let us know if you see further issues. I'll close this for now, feel free to ping me if it needs to be re-opened.
