### ISSUE TITLE
Failure to pull docker image does not result in failed buil

### ISSUE THREAD

**Issue by stevendanna** [buildkite-plugins/docker-buildkite-plugin#109]
Because of a misconfiguration in our pipeline, we recently discovered that a failure to pull the configured docker image does not result in a failed build (screenshot attached).

I believe the problem is here

https://github.com/buildkite-plugins/docker-buildkite-plugin/blob/master/hooks/command#L221-L226

I /think/ the issue is that combining `if !` and `$?` doesn't work as that code expects. Consider:

```
> cat ./test.sh 
#!/bin/bash

set -euo pipefail

if ! false; then
    rv=$?
    echo "RV is $rv"
fi
> ./test.sh 
RV is 0
```

<img width="946" alt="screen shot 2019-02-26 at 2 38 12 pm" src="https://user-images.githubusercontent.com/852371/53422026-98bfc500-39d6-11e9-94e2-d477cdffba0f.png">

**Comment by frangz** [comment]
+1 to this

This bug makes the entire plugin unusable for us :(

**Comment by lox** [comment]
Sorry about that folks! We'll get a fix out soon.
