### ISSUE TITLE
copy-checkout

### ISSUE THREAD

**Issue by GaryPWhite** [buildkite-plugins/docker-buildkite-plugin#113]
We've run into situations where the directory mounted in the container gets into a bad state, and the buildkite-agent user isn't privileged enough to delete the contents of the directory.

We had a couple solutions in mind, one of the most reasonable of which we thought would be using the `docker cp` command to put the checked-out directory into the container. Another way we could accomplish this is by injecting a few commands to mount read-only volumes and copying them through the container to avoid any changes propogating, but `docker cp` seems like a cleaner solution.

Would be willing to put in a PR to mirror the usage of `mount-checkout`, but for `docker cp`'ing a directory into the container/image at runtime. Would like to hear your thoughts!

**Comment by pzeballos** [comment]
Hey @GaryPWhite! There's a WIP PR #182 that should fix this. If you are still interested, you can contribute to that one. Thanks!
