### ISSUE TITLE
Enable docker buildkit

### ISSUE THREAD

**Issue by shavo007** [buildkite-plugins/docker-buildkite-plugin#118]
This is a feature request

Enable buildkit to improve performance

https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds

raised here too https://github.com/seek-oss/docker-ecr-cache-buildkite-plugin/issues/12

**Comment by lox** [comment]
Can you just set DOCKER_BUILDKIT=1 as an env?

**Comment by shavo007** [comment]
yep, can do. it was more to raise visibility of the feature here.

**Comment by lox** [comment]
Totally, very valid question! I've been wondering myself what the best way to make it easy for folks to experiment with Buildkit is 🤔
