### ISSUE TITLE
Possibility to see output from command

### ISSUE THREAD

**Issue by mrsimo** [buildkite-plugins/docker-buildkite-plugin#134]
Our deploy pipeline is basically a docker run using this plugin. For other pipelines it wouldn't matter, but deploys... you do open it and want to see how it's going while it runs.

At the moment every time I open this pipeline I need to go and click on the tiny line that says "Running command in <docker image>" so I can see the output. Would it be possible to have this block of logs open as default? Or configurable? I guess it'd mean changing this to a `+++`... no?

https://github.com/buildkite-plugins/docker-buildkite-plugin/blob/0d9b114b0ca8ec7167787285274aa3842392374d/hooks/command#L356

What do you all think?

**Comment by pzeballos** [comment]
Hey @mrsimo! Sorry for this very late reply! 😅 You are welcome to fork the repo and add that functionality (which you probably did 😛), but we want to keep consistency on the logs, and by default, we only expand the last one. Adding a new expanded group would add a lot of noise and many users prefer to have it collapse. Thanks!
