### ISSUE TITLE
support -p to allow exposing ports

### ISSUE THREAD

**Issue by joscha** [buildkite-plugins/docker-buildkite-plugin#144]
I tried using the `shell` option , but unfortunately the constructed command is still invalid:

```
[...] --label com.buildkite.job-id=c691aa38-56e7-4abb-8acc-8546b863420d my/image0 -p 80:8080 /bin/sh -e -c my/script.sh
```

it needs to be:

```
[...] --label com.buildkite.job-id=c691aa38-56e7-4abb-8acc-8546b863420d -p 80:8080 my/image0 /bin/sh -e -c my/script.sh
```

**Comment by joscha** [comment]
interestingly it looks like https://github.com/buildkite-plugins/docker-buildkite-plugin/blob/5745e8f7f3cc99343b25bb57381288192df3331c/hooks/command#L306-L318 should allow this if I do:

```
      - 'docker#v3.3.0':
          image: 'my/image'
          debug: false
          shell:
            - '-p'
            - '80:8080'
            - /bin/sh
            - '-e'
            - '-c'
          workdir: /workdir
```

**Comment by joscha** [comment]
ah no, the shell args are added later on to the `args` array: https://github.com/buildkite-plugins/docker-buildkite-plugin/blame/5745e8f7f3cc99343b25bb57381288192df3331c/hooks/command#L347

**Comment by lox** [comment]
Am I right in understanding you basically want a `ports` property supported?
