### ISSUE TITLE
mount-buildkite-agent being `true` by default is a footgun

### ISSUE THREAD

**Issue by richvdh** [buildkite-plugins/docker-buildkite-plugin#149]
We're using the docker-buildkite-plugin to achieve a basic level of build isolation to make it safer to run pull requests from third-party forked repositories.

However, for this to be effective, we need to make sure we set `mount-buildkite-agent: false` for each invocation of the docker-buildkite-plugin, as otherwise the agent token is leaked into the docker container, allowing a malicious PR author to run arbitrary pipelines on our build agents.

I'd like to suggest that `mount-buildkite-agent` should be false by default.

**Comment by toote** [comment]
This is a great suggestion. I have created #211 implementing the change which will result in an update to the major version of the plugin as it would be a backwards-incompatible change
