### ISSUE TITLE
propagate-environment: true should be the default

### ISSUE THREAD

**Issue by frankh** [buildkite-plugins/docker-buildkite-plugin#164]
I don't think I've made a single pipeline step using the docker plugin that doesn't use `propagate-environment: true`

Is there a good reason the default is not to propagate this?

I suppose this would have to be the 4.0 release as it would break some pipelines but I think it would be worth the change

**Comment by lox** [comment]
I agree!

**Comment by ngan** [comment]
I agree as well. 🤔 @frankh do you have specific examples for why it would break existing pipelines if we change this default?

**Comment by frankh** [comment]
It's technically possible to have a pipeline that relies on the lack of an environment variable (e.g. some tools have different behaviour if `CI=true` is set or not)

Some people may be relying on this behaviour and it would break if it changes, but I imagine it would be quite rare

**Comment by toote** [comment]
There may also be security considerations. For example, cloud access credentials or tokens that you probably don't want to share by default. While I understand that your use case does lead to a lot of repetition, changing it will probably have those that don't need it create the very same issue with the opposite suggestion.

I believe the current default leads to the least amount of surprises in the long run and makes it quite obvious when information is being shared into the container.
