### ISSUE TITLE
docker: context canceled

### ISSUE THREAD

**Issue by joscha** [buildkite-plugins/docker-buildkite-plugin#165]
I have been seeing this lately a few times:

```
--
  | Status: Downloaded newer image for xxx.dkr.ecr.us-east-1.amazonaws.com/xxx
  | docker: Error response from daemon: read unix @->@/containerd-shim/moby/d721e6f8e219ff658794631a57c7612144095d7cd4d4ece099053c7ceecb8316/shim.sock: read: connection reset by peer: unknown.
  | ERRO[0061] error waiting for container: context canceled
```

is anyone seeing the same thing? I am unsure yet whether it is related to the plugin or not. Is there a chance the plugin could help recover from this? A retry of the step passes every time.

**Comment by jayco** [comment]
@joscha hmmm, weird! 

We have not had any other reports of users experiencing the same issue, how often are you seeing this?

**Comment by joscha** [comment]
it recurs fairly regularly but not regular enough to cause massive fallout - do you have any idea what this could be?

**Comment by jayco** [comment]
Not really. I did a quick google found other similar issues users were having https://github.com/moby/moby/issues/38742.

I don't think this issue is related to the plugin.

**Comment by joscha** [comment]
Okay, will close for the time being. Thanks for looking into it.
