### ISSUE TITLE
BUILDKITE_PLUGIN_DOCKER_IMAGE: unbound variable

### ISSUE THREAD

**Issue by CHR15-** [buildkite-plugins/docker-buildkite-plugin#168]
Hi!

`/var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-docker-buildkite-plugin-v3-5-0/hooks/command: line 339: BUILDKITE_PLUGIN_DOCKER_IMAGE: unbound variable`

This has started occurring on our agents and nothing has changed from our end! Any ideas what this could be?

**Comment by CHR15-** [comment]
This is now fixed 👍

**Comment by zzak** [comment]
I just ran into this exact same thing, but haven't figured out why yet. 🤔
