### ISSUE TITLE
Plugin fails to execute a step inside Kubernetes

### ISSUE THREAD

**Issue by arikkfir** [buildkite-plugins/docker-buildkite-plugin#17]
I'm running a Kubernetes cluster with [BuildKite running as a pod](https://buildkite.com/docs/agent/v3/gcloud#running-the-agent-on-google-container-engine)
Builds are running great, except when I'm using this plugin, which causes the following error (ANSI chars removed):

```~~~ Running plugin github.com/buildkite-plugins/docker-buildkite-plugin#v1.1.1 command hook
/buildkite/plugins/github-com-buildkite-plugins-docker-buildkite-plugin-v1-1-1/hooks/command
--- :docker: Running - yum install -y https://centos7.iuscommunity.org/ius-release.rpm
- yum install -y python36u python36u-pip git
- pip3.6 --disable-pip-version-check --no-cache-dir install -r requirements.txt
- COVERALLS_REPO_TOKEN="$(cat /buildkite/secrets/coveralls-token.txt)" ./test.sh
 in centos:7.4.1708
docker: Error response from daemon: error while creating mount source path '/buildkite/builds/buildkite-agent-7857746466-fcbd9/kfirz/deployster': mkdir /buildkite: read-only file system.
Error: The plugin github.com/buildkite-plugins/docker-buildkite-plugin#v1.1.1 command hook exited with status 125
```

The BuildKite has Docker binary & socket mounted as volumes from the hosting node.

**Comment by lox** [comment]
It looks like Kubernetes / Container OS mounts the root partition as read-only, so when the docker plugin tries to mount in the $PWD it fails: https://github.com/buildkite-plugins/docker-buildkite-plugin/blob/ffa89d937dd249f508ff1f491af306b81990bd6b/hooks/command#L16

I'm afraid I don't have much context why this is happening, but I suspect the answer might be to use source volumes vs host mounts. @sj26 do you have any ideas?

**Comment by arikkfir** [comment]
There's another issue at buildkite/agent/issues/729 that seems relevant.

**Comment by lox** [comment]
Thanks @arikkfir, let's consolidate on buildkite/agent#729. I've posted a suggested fix there.
