### ISSUE TITLE
Pull request tests are building on the wrong repository

### ISSUE THREAD

**Issue by albertyw** [buildkite-plugins/docker-buildkite-plugin#176]
I've noticed that many of the currently open pull requests are failing on the last step because the build is trying to checkout the test branch from the buildkite-plugins repository rather than the forked repository.  This can be most easily seen in #174 ([build](https://buildkite.com/buildkite/plugins-docker/builds/21#59c8a8f8-6a8a-4107-a796-9b5e75d9709b)) and #175 ([build](https://buildkite.com/buildkite/plugins-docker/builds/22#5043a0cc-1395-4acc-9386-dac9646a22e6)).  They have logs of the form

```
  | [2021-01-11T04:53:08Z] $ git clone -v -- https://github.com/buildkite-plugins/docker-buildkite-plugin.git .
...
  | [2021-01-11T04:53:08Z] # Checking out `866a6bc4b36af4af0a7b75118177092333c8b0b9`
```

The commit hash exists on [github.com:albertyw/docker-buildkite-plugin](https://github.com/albertyw/docker-buildkite-plugin/commit/866a6bc4b36af4af0a7b75118177092333c8b0b9) and not on [github.com:buildkite-plugins/docker-buildkite-plugin](https://github.com/buildkite-plugins/docker-buildkite-plugin/commit/866a6bc4b36af4af0a7b75118177092333c8b0b9)

**Comment by chloeruka** [comment]
Hey @albertyw – good catch! Thanks for pointing this out. I'm drafting a fix for this, I'll aim to roll it out shortly.
