### ISSUE TITLE
Can't interpolate ENV vars in mount path

### ISSUE THREAD

**Issue by mvastola** [buildkite-plugins/docker-buildkite-plugin#189]
_Note: This seems related to #185, but the workaround suggested does not apply for my use case._

I just submitted buildkite-plugins/ecr-buildkite-plugin#72, but I'm not sure where the issue lies. 

TL;DR: I'm trying to mount my `${DOCKER_CONFIG}` folder into a docker container, but it appears the `ecr` plugin isn't setting it in such a way that I can't simply put `${DOCKER_CONFIG}:/home/user/.docker` in the `volumes` array.

Per the [docs](https://buildkite.com/docs/pipelines/secrets#anti-pattern-referencing-secrets-in-your-pipeline-yaml), however, it seems I _should_ be able to add an extra dollar sign (so, `$${DOCKER_CONFIG}:/home/user/.docker`) and make it work. However, for whatever reason, although `$${DOCKER_CONFIG}` is converted to `${DOCKER_CONFIG}`, it isn't expanded beyond that, and the literal string `${DOCKER_CONFIG}` is sent to `docker` as an argument.

Would it be possible to turn on interpolation for the volume paths so that this works?

**Comment by dubhunter** [comment]
I am having the same issue.

**Comment by toote** [comment]
I would be interested in understand what is the use-case for sharing the actual `DOCKER_CONFIG` path as a mount to the container.

From what I've understood reading the description, linked issue and links in there as well, the only variables that would pose an issue are those that change from job execution to job execution (all the others can probably be worked-around through differing the pipeline upload to when the variable do exist). Or am I missing something?

**Comment by mvastola** [comment]
@toote It allows you to provide credentials (this file is where they're stored for ECR by the aws CLI) and similar info (if a host uses a credential provider) to the container so it can do pushes/pulls.
