### ISSUE TITLE
Changing the Docker Version from 20.10.9 to 20.10.22

### ISSUE THREAD

**Issue by frankpengau** [buildkite-plugins/docker-buildkite-plugin#228]
Just realised that [docker-buildkite-plugin buildkite pipeline](https://buildkite.com/buildkite/plugins-docker) is exporting an older version of docker. Maybe we should update it to the latest docker engine version (20.10.22)?

Currently:
```
🌏 Setting up environment variables
...
export DOCKER_VERSION="20.10.9"
...
```

**Comment by toote** [comment]
@frankpengau while a good idea, unfortunately that is not something to do with this plugin. It is just the version run in the agents that took care of this pipeline. I trust that the buildkite system engineers will take care of that in due time but even if they did the update today, assuming they are using their own [AWS Elastic Stack](https://github.com/buildkite/elastic-ci-stack-for-aws/], it [would only be updated to 20.10.17](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/6a52684d17094876e3ff3e6e78251c0ef94c32dd/packer/linux/scripts/install-docker.sh)
