### ISSUE TITLE
Documentation: expand-volume-vars expansion time

### ISSUE THREAD

**Issue by jamesatwill-okta** [buildkite-plugins/docker-buildkite-plugin#234]
Could you add a note to `expand-volume-vars` that `$FOO` is expanded at pipeline upload time, so if you want variables at runtime you need to specify `$$FOO` ? While it makes sense, this is likely not what people are expecting (I sure wasn't) when they're using this feature.

**Comment by toote** [comment]
Sounds like a great idea and quite a simple change to the documentation. Care to try to create the PR with the suggestion?

**Comment by jamesatwill-okta** [comment]
https://github.com/buildkite-plugins/docker-buildkite-plugin/pull/235/files
