### ISSUE TITLE
Files created while running in a container are created as root user

### ISSUE THREAD

**Issue by Regner** [buildkite-plugins/docker-buildkite-plugin#3]
When the buildkite-agent runs a second time it cannot cleanup the git directory because it doesn't own the files created by the previous build in the docker container.

Is there a recommended way of dealing with this? Adding a hook that runs another container and does a chown of some kind would probably work, but I was hoping for something a little more clean.

**Comment by lox** [comment]
We use a script that we allow via sudo for the buildkite-agent user to reset permissions as part of the environment hook: https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/conf/buildkite-agent/scripts/fix-buildkite-agent-builds-permissions

It's a horrible hack though

If you are running your own docker's, I'd be inclined to try running docker with user namespace remapping: https://success.docker.com/KBase/Introduction_to_User_Namespaces_in_Docker_Engine

That way you can map the UID of root in your containers to that of the user that runs buildkite-agent on the host.

**Comment by Regner** [comment]
OK, I think I will look into the second option. Thanks!

**Comment by Regner** [comment]
Ended up going with the first option, don't have time myself right now but would be great to have that a documented thing.

Thanks for a great product and quick followup, much appreciated.
