### ISSUE TITLE
Having /app mounted was surprising

### ISSUE THREAD

**Issue by aussiegeek** [buildkite-plugins/docker-buildkite-plugin#38]
I traditionally use `/app` for where the app in the container lives, so having this mounted for the buildkite-agent path lead to some debugging confusion

**Comment by aussiegeek** [comment]
Oh, I see where I went wrong, WORKDIR sets the mount path not, the docker WORKDIR as I expected

**Comment by lox** [comment]
Apologies @aussiegeek, it's confusing as it is now, we're planning on changing it in a major version bump at some point.
