### ISSUE TITLE
Ability to specify a local dockerfile to build and use

### ISSUE THREAD

**Issue by Regner** [buildkite-plugins/docker-buildkite-plugin#4]
Right now the Docker plugin only supports specifying an existing docker image. It would be really awesome to be able to specify a local dockerfile and have that built and used. The docker compose plugin supports this now and I am using that for now.

**Comment by lox** [comment]
I had a go at this @Regner. It introduces a lot of complexity that I'm not sure is worth having in this when it exists in the docker-compose plugin. Let me think it over some more!

**Comment by Regner** [comment]
Cool, thanks for taking a stab at it.

**Comment by mikeknox** [comment]
I've added it to my fork, PR: https://github.com/buildkite-plugins/docker-buildkite-plugin/pull/5

**Comment by bjeanes** [comment]
FWIW, I also would like this option if a clean way to accomplish it can be found. The agent v2 mechanism of `BUILDKITE_DOCKER` supported this and its deprecation notice points users here, which does not have equivalent functionality. At least, some documentation improvements related to that deprecation might be merited. What do you think?

**Comment by lox** [comment]
Yup, agree. Been trying to decide where it fits best.

**Comment by toolmantim** [comment]
We’ve added a link to the readme now, so I think we can close this here. Thanks for the great feedback!

**Comment by nhooyr** [comment]
Building images is a part of docker, not docker compose. Building images is orthogonal from multiple containers, which is the main feature of docker compose. It feels wrong for this feature to only be in the docker compose plugin. I don't need to use compose but I'd still like my tests to run in a Dockerfiles provided within my repository.

**Comment by toolmantim** [comment]
Completely! But you’d need to provide all the `docker build` cli options, and probably `push` too — the scope of this plugin is just `docker run` and perhaps should be called that.

Most people in your situation have either just written the Docker commands in the `command` section of their pipeline.yml if they need. Or in a shell script. I’d be curious what your use case is though, if that doesn’t feel right.

**Comment by lox** [comment]
FWIW @nhooyr, we've tried this multiple times and it just ends up complicated and duplicates the same work in `docker-compose`. We'd welcome a `docker-build` plugin if you felt inclined to try one out though!

**Comment by nhooyr** [comment]
> Most people in your situation have either just written the Docker commands in the `command` section of their pipeline.yml if they need. Or in a shell script. I’d be curious what your use case is though, if that doesn’t feel right.

It's just nicer to use a plugin and keep docker separate from the commands I want to run.

> FWIW @nhooyr, we've tried this multiple times and it just ends up complicated and duplicates the same work in `docker-compose`. We'd welcome a `docker-build` plugin if you felt inclined to try one out though!

Is it possible you an abstract out the image building into a shell library? And then use it in both plugins?

**Comment by kymikoloco** [comment]
Is there a different plugin from docker-compose that can do this functionality? Docker-compose doesn't ([currently](https://github.com/compose-spec/compose-spec/issues/81)) allow secrets mounted for build, so I have to bootstrap build using `docker build` but since commands aren't guaranteed to run on the same agent, I literally cannot use either plugin to build a Dockerfile and run commands inside it on the same agent, I have to write shell scripts to do everything.
