### ISSUE TITLE
entrypoint should allow ""

### ISSUE THREAD

**Issue by rcoup** [buildkite-plugins/docker-buildkite-plugin#59]
https://github.com/buildkite-plugins/docker-buildkite-plugin/blob/master/hooks/command#L82 checks for a non-empty string in `entrypoint`, but it should allow `""` so you can reset the entrypoint without having to do weird things like `entrypoint: "/bin/sh"; shell: "-ec"`

**Comment by toolmantim** [comment]
Yep, great idea! 👍🏼

**Comment by lox** [comment]
YAML has the concept of ~ as nil. I wonder if `entrypoint: ~` would work. Alternately `entrypoint: ⚡️` 😁
