### ISSUE TITLE
ENV vars only passed when mounting the agent

### ISSUE THREAD

**Issue by blsmth** [buildkite-plugins/docker-buildkite-plugin#60]
i'm trying to run a buildkite agent on OSX to run a CentOS docker image to run some jobs.   Since i can't mount the OSX darwin build in a linux container, I am shipping the container with the agent baked in and setting BUILDKITE_PLUGIN_DOCKER_MOUNT_BUILDKITE_AGENT=0.   That gets me up and running but i'm unable to use the buildkite-agent to upload or download artifacts because BUILD_ID is not passed along because of the logic behind the mount - https://github.com/buildkite-plugins/docker-buildkite-plugin/blob/master/hooks/command#L36

for now i think i can workaround by explicitly passing the needed 3 ENV vars, but it would be nice if they were passed through automatically, always, or at least with an option.

**Comment by lox** [comment]
We've recently added `propagate-environment` (https://github.com/buildkite-plugins/docker-buildkite-plugin/pull/80) to pass in all the env to the container. In future we'd like to make it the default, let us know if that solves your problem.
