### ISSUE TITLE
allow using Dockerfile inside repository

### ISSUE THREAD

**Issue by nhooyr** [buildkite-plugins/docker-buildkite-plugin#97]
Instead of just an image name.

**Comment by toolmantim** [comment]
Hi @nhooyr! Building images is out of the scope of this plugin I’m afraid, as it’d make this plugin complicated to maintain, and harder to use with new options that would be required.

Have you seen https://github.com/buildkite-plugins/docker-compose-buildkite-plugin which is designed for this exact use case?

**Comment by nhooyr** [comment]
thanks
